# pylint: disable=E1101,C0103,C0111
# revision identifiers, used by Alembic.
revision = '3c2efd86905b'
down_revision = 'b53e593b43b5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'current_phase')
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("No downgrades.")
    # pylint: disable=W0101
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'plans', sa.Column(
            'current_phase', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
