# pylint: disable=E1101,C0103,C0111
# revision identifiers, used by Alembic.
revision = '46c857af5e01'
down_revision = '11968cfd6155'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'next_phases')
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("No downgrades.")
    # pylint: disable=W0101
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'plans', sa.Column('next_phases', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###
