# pylint: disable=E1101,C0103,C0111
# revision identifiers, used by Alembic.
revision = '617c16d47585'
down_revision = 'b0ce3f579aee'
branch_labels = None
depends_on = None

from alembic import op
from litp.data.constants import LIVE_MODEL_ID
import sqlalchemy as sa


def upgrade():
    op.add_column('extensions', sa.Column('model_id', sa.Unicode(),
        nullable=False, server_default=LIVE_MODEL_ID))

    op.drop_index('ix_extensions_classpath', table_name='extensions')
    op.create_index(op.f('ix_extensions_classpath_model_id'), 'extensions',
            ['classpath', 'model_id'], unique=True)

    op.drop_constraint(op.f('pk_extensions'), "extensions")
    op.create_primary_key("pk_extensions", "extensions", ["name", "model_id"])


def downgrade():
    raise NotImplementedError("No downgrades.")
    # pylint: disable=W0101
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extensions_classpath_model_id'),
            table_name='extensions')
    op.create_index('ix_extensions_classpath', 'extensions', ['classpath'],
            unique=True)
    op.drop_column('extensions', 'model_id')
    ### end Alembic commands ###
