# pylint: disable=E1101,C0103,C0111
# revision identifiers, used by Alembic.
revision = 'b53e593b43b5'
down_revision = '617c16d47585'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_options'))
    )
    ### end Alembic commands ###


def downgrade():
    raise NotImplementedError("No downgrades.")
    # pylint: disable=W0101
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_options')
    ### end Alembic commands ###
